name: Deploy on Github pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout🛎️
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Clean build directory
      run: rm -rf ./build
    - name: Install and Build 📚
      run: |
        npm install -g pnpm
        pnpm install
        pnpm run build 
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
